### ISSUE TITLE
Build failures with openSUSE's CMake parameters

### ISSUE THREAD

**Issue by surprized** [Kaffeine/telepathy-ofono#14]
[Full build log.](https://github.com/TelepathyIM/telepathy-ofono/files/6192780/_log.txt)

Seems to have something to do with it being dynamically linked, because when I was building it static it didn't have problems. The branch is _staging_.

Mind taking a look to see what could the solution be?

**Comment by simonschmeisser** [comment]
mcp-account-manager-ofono-on-ring seems to need to be linked glib but is not somehow?

**Comment by simonschmeisser** [comment]
https://github.com/TelepathyIM/telepathy-ofono/blob/b9bfed49157fd16c4a3dc84d29bdc5656beba5c9/CMakeLists.txt#L42

should add that but maybe doesn't?

**Comment by Kaffeine** [comment]
> [Full build log.](https://github.com/TelepathyIM/telepathy-ofono/files/6192780/_log.txt)
> 
`_log.txt:3217`:
/usr/bin/c++ -fPIC -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -DNDEBUG -O2 -g -DNDEBUG -flto=auto -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now -shared -Wl,-soname,mcp-account-manager-ofono.so -o mcp-account-manager-ofono.so CMakeFiles/mcp-account-manager-ofono.dir/mcp-account-manager-ofono_autogen/mocs_compilation.cpp.o CMakeFiles/mcp-account-manager-ofono.dir/mission-control-plugin.c.o CMakeFiles/mcp-account-manager-ofono.dir/mcp-account-manager-ofono-on-ring.c.o  -lmission-control-plugins -ltelepathy-glib 

Glib is not linked. As far as I understand, linking against `telepathy-glib` is not enough, especially when you have `-Wl,--no-undefined`. Probably this linker flag is not turned on on other builds (without this flag the build 'll succeed).

It is an error in the build, I'll try to fix it soon.

**Comment by Kaffeine** [comment]
> when I was building it static it didn't have problems. 

`-Wl,--no-undefined` works only for ELF files (shared libraries or executables). Static libraries has no linking table so the flag does nothing.

**Comment by Kaffeine** [comment]
This is a non-default linker behavior (by default linkers do not check symbols on linkage) but I think we should support it.

**Comment by simonschmeisser** [comment]
```
pkg-config mission-control-plugins --libs
-lmission-control-plugins -ltelepathy-glib

pkg-config mission-control-plugins --print-requires
telepathy-glib

pkg-config telepathy-glib --libs
-ltelepathy-glib 


pkg-config telepathy-glib --print-requires


```
Shouldn't that in an ideal world contain `glib`?

**Comment by Kaffeine** [comment]
> ```
> pkg-config telepathy-glib --print-requires
> ```
> 
> Shouldn't that in an ideal world contain `glib`?

Sure it should. Maybe it would fix the build.

And yet, as the plugin source code directly uses glib, it still should explicitly links against it.

**Comment by surprized** [comment]
For now I'll remove --no-undefined from the build flags, it should not cause major issues, right?

**Comment by Kaffeine** [comment]
Fixed by (any of) https://github.com/TelepathyIM/telepathy-ofono/commit/8436bc4c4d1c6156bf6c573e701e9650f5faacf0 in this project and https://github.com/TelepathyIM/telepathy-mission-control/commit/2a927f69f78c54be80862eff3bfd86a80b703eb8 in the mission-control.

**Comment by surprized** [comment]
Thanks!
